<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ApplicationServices\ApplicationServices.csproj" />
    <ProjectReference Include="..\AssertionHelper\AssertionHelper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
  </ItemGroup>

</Project>
