<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="ClosedXML" Version="0.105.1">
      <PrivateAssets>compile;contentFiles;build;buildMultitargeting;buildTransitive;analyzers;native</PrivateAssets>
	</PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DtoImporterService\DtoImporterService.csproj" />
    <ProjectReference Include="..\LibationSearchEngine\LibationSearchEngine.csproj" />
    <ProjectReference Include="..\DataLayer.Postgres\DataLayer.Postgres.csproj" />
    <ProjectReference Include="..\DataLayer.Sqlite\DataLayer.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
  </ItemGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

</Project>
